// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20211207185124_dummydata")]
    partial class dummydata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YearReleased")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d55ed87-c56c-4aed-8a3e-f469734cbacf"),
                            Author = "J.Guillou",
                            Rating = 5,
                            Title = "Ondskan",
                            YearReleased = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2007)
                        },
                        new
                        {
                            Id = new Guid("84c785e8-cc0d-42bd-afd6-0e3534691063"),
                            Author = "V. Moberg",
                            Rating = 5,
                            Title = "Utvandrarna",
                            YearReleased = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1949)
                        },
                        new
                        {
                            Id = new Guid("58ebe209-350c-4517-933a-d418fd175ca3"),
                            Author = "Daniel Defoe",
                            Rating = 4,
                            Title = "Robinson Crusoe",
                            YearReleased = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1719)
                        },
                        new
                        {
                            Id = new Guid("2acc3817-6640-4010-92bd-3c05d18bcc14"),
                            Author = "Marcel Proust",
                            Rating = 4,
                            Title = " In Search of Lost Time",
                            YearReleased = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1913)
                        },
                        new
                        {
                            Id = new Guid("70d5682a-414c-48ea-9ff0-5cf51180a172"),
                            Author = "Miguel de Cervantes",
                            Rating = 5,
                            Title = "Don Quixote",
                            YearReleased = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1605)
                        },
                        new
                        {
                            Id = new Guid("bbf1ffea-c567-4089-b83e-0cc553eb6933"),
                            Author = "Herman Melville",
                            Rating = 5,
                            Title = "Moby Dick",
                            YearReleased = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1851)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
